### ISSUE TITLE
`java.awt.HeadlessException: No X11 DISPLAY variable was set` when using `gol help` command in non-graphical environment

### ISSUE THREAD

**Issue by docentYT** [clarisma/gol-tool#102]
When I try to use the `gol help` command in a non-GUI environment I get the below error:

```
Internal error:                                                  
No X11 DISPLAY variable was set,
or no headful library support was found,
but this program performed an operation which requires it,

java.awt.HeadlessException:
No X11 DISPLAY variable was set,
or no headful library support was found,
but this program performed an operation which requires it,

        at java.desktop/java.awt.Desktop.getDesktop(Desktop.java:302)
        at com.geodesk.gol.HelpCommand.perform(HelpCommand.java:27)
        at com.clarisma.common.cli.Application.run(Application.java:98)
        at com.geodesk.gol.GolTool.main(GolTool.java:48)
```

Since the `gol help` command redirects to a website instead of displaying text in terminal, it would be better to check whether the website was successfully opened and, if not, display the URL address in console.

**Comment by clarisma** [comment]
Thanks for submitting this!

Ideally, we should display plain-text help in that case, but in the interim, displaying the URL is better than failing with an error.
