### ISSUE TITLE
[Regression] build: Validation failure

### ISSUE THREAD

**Issue by clarisma** [clarisma/gol-tool#97]
(Affects only 0.1.5 dev)

```
  java.lang.NegativeArraySizeException: -154154042
	  at com.clarisma.common.io.PileFile.load(PileFile.java:340)
	  at com.geodesk.gol.build.Validator.loadTileData(Validator.java:374)
	  at com.geodesk.gol.build.Validator$Task.call(Validator.java:1852)
```

**Comment by clarisma** [comment]
Resolved (Caused by fix to #96)
